//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace App3.Droid.AscoTms {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="imcwp", Namespace="imcwp")]
    public partial class imcwp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageReplyOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback VehicleRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrailerRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback JourneyRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsignmentRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback JourneyStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatusRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocumentRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public imcwp() {
            this.Url = "http://10.0.100.45:29791";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = false;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event MessageRequestCompletedEventHandler MessageRequestCompleted;
        
        /// <remarks/>
        public event MessageReplyCompletedEventHandler MessageReplyCompleted;
        
        /// <remarks/>
        public event MessageTemplateCompletedEventHandler MessageTemplateCompleted;
        
        /// <remarks/>
        public event VehicleRequestCompletedEventHandler VehicleRequestCompleted;
        
        /// <remarks/>
        public event TrailerRequestCompletedEventHandler TrailerRequestCompleted;
        
        /// <remarks/>
        public event JourneyRequestCompletedEventHandler JourneyRequestCompleted;
        
        /// <remarks/>
        public event ConsignmentRequestCompletedEventHandler ConsignmentRequestCompleted;
        
        /// <remarks/>
        public event JourneyStatusCompletedEventHandler JourneyStatusCompleted;
        
        /// <remarks/>
        public event StatusRequestCompletedEventHandler StatusRequestCompleted;
        
        /// <remarks/>
        public event DocumentRequestCompletedEventHandler DocumentRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("strLogin-LoginResponse", Namespace="imcwp")]
        public strLoginLoginResponse Login([System.Xml.Serialization.XmlElementAttribute("Login", Namespace="imcwp")] Login Login1) {
            object[] results = this.Invoke("Login", new object[] {
                        Login1});
            return ((strLoginLoginResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(Login Login1) {
            this.LoginAsync(Login1, null);
        }
        
        /// <remarks/>
        public void LoginAsync(Login Login1, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Login1}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("strMessageRequest-MessageResponse", Namespace="imcwp")]
        public strMessageRequestMessageResponse MessageRequest([System.Xml.Serialization.XmlElementAttribute("MessageRequest", Namespace="imcwp")] MessageRequest MessageRequest1) {
            object[] results = this.Invoke("MessageRequest", new object[] {
                        MessageRequest1});
            return ((strMessageRequestMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void MessageRequestAsync(MessageRequest MessageRequest1) {
            this.MessageRequestAsync(MessageRequest1, null);
        }
        
        /// <remarks/>
        public void MessageRequestAsync(MessageRequest MessageRequest1, object userState) {
            if ((this.MessageRequestOperationCompleted == null)) {
                this.MessageRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageRequestOperationCompleted);
            }
            this.InvokeAsync("MessageRequest", new object[] {
                        MessageRequest1}, this.MessageRequestOperationCompleted, userState);
        }
        
        private void OnMessageRequestOperationCompleted(object arg) {
            if ((this.MessageRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageRequestCompleted(this, new MessageRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("strMessageReply-MessageReceived", Namespace="imcwp")]
        public strMessageReplyMessageReceived MessageReply([System.Xml.Serialization.XmlElementAttribute("MessageReply", Namespace="imcwp")] MessageReply MessageReply1) {
            object[] results = this.Invoke("MessageReply", new object[] {
                        MessageReply1});
            return ((strMessageReplyMessageReceived)(results[0]));
        }
        
        /// <remarks/>
        public void MessageReplyAsync(MessageReply MessageReply1) {
            this.MessageReplyAsync(MessageReply1, null);
        }
        
        /// <remarks/>
        public void MessageReplyAsync(MessageReply MessageReply1, object userState) {
            if ((this.MessageReplyOperationCompleted == null)) {
                this.MessageReplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageReplyOperationCompleted);
            }
            this.InvokeAsync("MessageReply", new object[] {
                        MessageReply1}, this.MessageReplyOperationCompleted, userState);
        }
        
        private void OnMessageReplyOperationCompleted(object arg) {
            if ((this.MessageReplyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageReplyCompleted(this, new MessageReplyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strMessageTemplate-TemplateResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Template", IsNullable=false)]
        public strTemplateResponseTemplate[] MessageTemplate([System.Xml.Serialization.XmlElementAttribute("MessageTemplate", Namespace="imcwp")] MessageTemplate MessageTemplate1) {
            object[] results = this.Invoke("MessageTemplate", new object[] {
                        MessageTemplate1});
            return ((strTemplateResponseTemplate[])(results[0]));
        }
        
        /// <remarks/>
        public void MessageTemplateAsync(MessageTemplate MessageTemplate1) {
            this.MessageTemplateAsync(MessageTemplate1, null);
        }
        
        /// <remarks/>
        public void MessageTemplateAsync(MessageTemplate MessageTemplate1, object userState) {
            if ((this.MessageTemplateOperationCompleted == null)) {
                this.MessageTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageTemplateOperationCompleted);
            }
            this.InvokeAsync("MessageTemplate", new object[] {
                        MessageTemplate1}, this.MessageTemplateOperationCompleted, userState);
        }
        
        private void OnMessageTemplateOperationCompleted(object arg) {
            if ((this.MessageTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageTemplateCompleted(this, new MessageTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strVehicleRequest-VehicleResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Vehicle", IsNullable=false)]
        public strVehicleResponseVehicle[] VehicleRequest([System.Xml.Serialization.XmlElementAttribute("VehicleRequest", Namespace="imcwp")] VehicleRequest VehicleRequest1) {
            object[] results = this.Invoke("VehicleRequest", new object[] {
                        VehicleRequest1});
            return ((strVehicleResponseVehicle[])(results[0]));
        }
        
        /// <remarks/>
        public void VehicleRequestAsync(VehicleRequest VehicleRequest1) {
            this.VehicleRequestAsync(VehicleRequest1, null);
        }
        
        /// <remarks/>
        public void VehicleRequestAsync(VehicleRequest VehicleRequest1, object userState) {
            if ((this.VehicleRequestOperationCompleted == null)) {
                this.VehicleRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVehicleRequestOperationCompleted);
            }
            this.InvokeAsync("VehicleRequest", new object[] {
                        VehicleRequest1}, this.VehicleRequestOperationCompleted, userState);
        }
        
        private void OnVehicleRequestOperationCompleted(object arg) {
            if ((this.VehicleRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VehicleRequestCompleted(this, new VehicleRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strTrailerRequest-TrailerResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Trailer", IsNullable=false)]
        public strTrailerResponseTrailer[] TrailerRequest([System.Xml.Serialization.XmlElementAttribute("TrailerRequest", Namespace="imcwp")] TrailerRequest TrailerRequest1) {
            object[] results = this.Invoke("TrailerRequest", new object[] {
                        TrailerRequest1});
            return ((strTrailerResponseTrailer[])(results[0]));
        }
        
        /// <remarks/>
        public void TrailerRequestAsync(TrailerRequest TrailerRequest1) {
            this.TrailerRequestAsync(TrailerRequest1, null);
        }
        
        /// <remarks/>
        public void TrailerRequestAsync(TrailerRequest TrailerRequest1, object userState) {
            if ((this.TrailerRequestOperationCompleted == null)) {
                this.TrailerRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrailerRequestOperationCompleted);
            }
            this.InvokeAsync("TrailerRequest", new object[] {
                        TrailerRequest1}, this.TrailerRequestOperationCompleted, userState);
        }
        
        private void OnTrailerRequestOperationCompleted(object arg) {
            if ((this.TrailerRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrailerRequestCompleted(this, new TrailerRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strJourneyRequest-JourneyResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Journey", IsNullable=false)]
        public strJourneyResponseJourney[] JourneyRequest([System.Xml.Serialization.XmlElementAttribute("JourneyRequest", Namespace="imcwp")] JourneyRequest JourneyRequest1) {
            object[] results = this.Invoke("JourneyRequest", new object[] {
                        JourneyRequest1});
            return ((strJourneyResponseJourney[])(results[0]));
        }
        
        /// <remarks/>
        public void JourneyRequestAsync(JourneyRequest JourneyRequest1) {
            this.JourneyRequestAsync(JourneyRequest1, null);
        }
        
        /// <remarks/>
        public void JourneyRequestAsync(JourneyRequest JourneyRequest1, object userState) {
            if ((this.JourneyRequestOperationCompleted == null)) {
                this.JourneyRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJourneyRequestOperationCompleted);
            }
            this.InvokeAsync("JourneyRequest", new object[] {
                        JourneyRequest1}, this.JourneyRequestOperationCompleted, userState);
        }
        
        private void OnJourneyRequestOperationCompleted(object arg) {
            if ((this.JourneyRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JourneyRequestCompleted(this, new JourneyRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strConsignmentRequest-ConsignmentResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Request", IsNullable=false)]
        public strConsignmentResponseRequest[] ConsignmentRequest([System.Xml.Serialization.XmlElementAttribute("ConsignmentRequest", Namespace="imcwp")] ConsignmentRequest ConsignmentRequest1) {
            object[] results = this.Invoke("ConsignmentRequest", new object[] {
                        ConsignmentRequest1});
            return ((strConsignmentResponseRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsignmentRequestAsync(ConsignmentRequest ConsignmentRequest1) {
            this.ConsignmentRequestAsync(ConsignmentRequest1, null);
        }
        
        /// <remarks/>
        public void ConsignmentRequestAsync(ConsignmentRequest ConsignmentRequest1, object userState) {
            if ((this.ConsignmentRequestOperationCompleted == null)) {
                this.ConsignmentRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsignmentRequestOperationCompleted);
            }
            this.InvokeAsync("ConsignmentRequest", new object[] {
                        ConsignmentRequest1}, this.ConsignmentRequestOperationCompleted, userState);
        }
        
        private void OnConsignmentRequestOperationCompleted(object arg) {
            if ((this.ConsignmentRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsignmentRequestCompleted(this, new ConsignmentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("strJourneyStatus-JourneyStatusResponse", Namespace="imcwp")]
        public strJourneyStatusJourneyStatusResponse JourneyStatus([System.Xml.Serialization.XmlElementAttribute("JourneyStatus", Namespace="imcwp")] JourneyStatus JourneyStatus1) {
            object[] results = this.Invoke("JourneyStatus", new object[] {
                        JourneyStatus1});
            return ((strJourneyStatusJourneyStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void JourneyStatusAsync(JourneyStatus JourneyStatus1) {
            this.JourneyStatusAsync(JourneyStatus1, null);
        }
        
        /// <remarks/>
        public void JourneyStatusAsync(JourneyStatus JourneyStatus1, object userState) {
            if ((this.JourneyStatusOperationCompleted == null)) {
                this.JourneyStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJourneyStatusOperationCompleted);
            }
            this.InvokeAsync("JourneyStatus", new object[] {
                        JourneyStatus1}, this.JourneyStatusOperationCompleted, userState);
        }
        
        private void OnJourneyStatusOperationCompleted(object arg) {
            if ((this.JourneyStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JourneyStatusCompleted(this, new JourneyStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strStatusRequest-StatusResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("StatusField", IsNullable=false)]
        public strStatusResponseStatusField[] StatusRequest([System.Xml.Serialization.XmlElementAttribute("StatusRequest", Namespace="imcwp")] StatusRequest StatusRequest1) {
            object[] results = this.Invoke("StatusRequest", new object[] {
                        StatusRequest1});
            return ((strStatusResponseStatusField[])(results[0]));
        }
        
        /// <remarks/>
        public void StatusRequestAsync(StatusRequest StatusRequest1) {
            this.StatusRequestAsync(StatusRequest1, null);
        }
        
        /// <remarks/>
        public void StatusRequestAsync(StatusRequest StatusRequest1, object userState) {
            if ((this.StatusRequestOperationCompleted == null)) {
                this.StatusRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatusRequestOperationCompleted);
            }
            this.InvokeAsync("StatusRequest", new object[] {
                        StatusRequest1}, this.StatusRequestOperationCompleted, userState);
        }
        
        private void OnStatusRequestOperationCompleted(object arg) {
            if ((this.StatusRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatusRequestCompleted(this, new StatusRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("strDocumentRequest-DocumentResponse", Namespace="imcwp")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
        public strDocumentResponseDocument[] DocumentRequest([System.Xml.Serialization.XmlElementAttribute("DocumentRequest", Namespace="imcwp")] DocumentRequest DocumentRequest1) {
            object[] results = this.Invoke("DocumentRequest", new object[] {
                        DocumentRequest1});
            return ((strDocumentResponseDocument[])(results[0]));
        }
        
        /// <remarks/>
        public void DocumentRequestAsync(DocumentRequest DocumentRequest1) {
            this.DocumentRequestAsync(DocumentRequest1, null);
        }
        
        /// <remarks/>
        public void DocumentRequestAsync(DocumentRequest DocumentRequest1, object userState) {
            if ((this.DocumentRequestOperationCompleted == null)) {
                this.DocumentRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocumentRequestOperationCompleted);
            }
            this.InvokeAsync("DocumentRequest", new object[] {
                        DocumentRequest1}, this.DocumentRequestOperationCompleted, userState);
        }
        
        private void OnDocumentRequestOperationCompleted(object arg) {
            if ((this.DocumentRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocumentRequestCompleted(this, new DocumentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class Login {
        
        private Header hdrField;
        
        private strLogin requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strLogin Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class Header {
        
        private System.DateTime timestampField;
        
        private string senderIdField;
        
        private string destinationIdField;
        
        private int versionField;
        
        private string uniqueKeyField;
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationId {
            get {
                return this.destinationIdField;
            }
            set {
                this.destinationIdField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UniqueKey {
            get {
                return this.uniqueKeyField;
            }
            set {
                this.uniqueKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strDocumentResponse-Document", Namespace="imcwp")]
    public partial class strDocumentResponseDocument {
        
        private string documentUrlField;
        
        private string documentFileNameField;
        
        private string documentDescriptionField;
        
        private int documentSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocumentUrl {
            get {
                return this.documentUrlField;
            }
            set {
                this.documentUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocumentFileName {
            get {
                return this.documentFileNameField;
            }
            set {
                this.documentFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocumentDescription {
            get {
                return this.documentDescriptionField;
            }
            set {
                this.documentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentSize {
            get {
                return this.documentSizeField;
            }
            set {
                this.documentSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strDocumentRequest {
        
        private string journeyIdField;
        
        private string jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JourneyId {
            get {
                return this.journeyIdField;
            }
            set {
                this.journeyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strStatusValue-StatusNext", Namespace="imcwp")]
    public partial class strStatusValueStatusNext {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strStatusField-StatusValue", Namespace="imcwp")]
    public partial class strStatusFieldStatusValue {
        
        private string statusField;
        
        private string statusTypeField;
        
        private string statusLabelField;
        
        private strStatusValueStatusNext[] statusNextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusLabel {
            get {
                return this.statusLabelField;
            }
            set {
                this.statusLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatusNext")]
        public strStatusValueStatusNext[] StatusNext {
            get {
                return this.statusNextField;
            }
            set {
                this.statusNextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strStatusResponse-StatusField", Namespace="imcwp")]
    public partial class strStatusResponseStatusField {
        
        private string fieldNameField;
        
        private strStatusFieldStatusValue[] statusValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatusValue")]
        public strStatusFieldStatusValue[] StatusValue {
            get {
                return this.statusValueField;
            }
            set {
                this.statusValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strStatusRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strJourneyStatusResponse-ValidStatus", Namespace="imcwp")]
    public partial class strJourneyStatusResponseValidStatus {
        
        private string nextStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NextStatus {
            get {
                return this.nextStatusField;
            }
            set {
                this.nextStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strJourneyStatus {
        
        private string journeyIdField;
        
        private string jobIdField;
        
        private string statusField;
        
        private System.DateTime timestampField;
        
        private string epodSigneeNameField;
        
        private string epodFileNameField;
        
        private string epodDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JourneyId {
            get {
                return this.journeyIdField;
            }
            set {
                this.journeyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EpodSigneeName {
            get {
                return this.epodSigneeNameField;
            }
            set {
                this.epodSigneeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EpodFileName {
            get {
                return this.epodFileNameField;
            }
            set {
                this.epodFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EpodData {
            get {
                return this.epodDataField;
            }
            set {
                this.epodDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strConsignmentResponse-Request", Namespace="imcwp")]
    public partial class strConsignmentResponseRequest {
        
        private string requestIdField;
        
        private string requestStatusField;
        
        private System.DateTime readyTimeField;
        
        private string materialField;
        
        private double weightField;
        
        private string quantityField;
        
        private string locationField;
        
        private bool aDRField;
        
        private string informationField;
        
        private string poField;
        
        private string contactNameField;
        
        private string contactNoField;
        
        private string dBTRField;
        
        private bool hCRField;
        
        private string ccuIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReadyTime {
            get {
                return this.readyTimeField;
            }
            set {
                this.readyTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public bool ADR {
            get {
                return this.aDRField;
            }
            set {
                this.aDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PO {
            get {
                return this.poField;
            }
            set {
                this.poField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DBTR {
            get {
                return this.dBTRField;
            }
            set {
                this.dBTRField = value;
            }
        }
        
        /// <remarks/>
        public bool HCR {
            get {
                return this.hCRField;
            }
            set {
                this.hCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CcuId {
            get {
                return this.ccuIdField;
            }
            set {
                this.ccuIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strConsignmentRequest {
        
        private string journeyIdField;
        
        private string jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JourneyId {
            get {
                return this.journeyIdField;
            }
            set {
                this.journeyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strJourney-Job", Namespace="imcwp")]
    public partial class strJourneyJob {
        
        private string jobIdField;
        
        private string jobStatusField;
        
        private string customerJobNoField;
        
        private string clientNameField;
        
        private string pickupNameField;
        
        private string pickupAddressField;
        
        private System.DateTime readyTimeField;
        
        private string materialField;
        
        private double weightField;
        
        private string quantityField;
        
        private string dropoffNameField;
        
        private string dropoffAddressField;
        
        private bool aDRField;
        
        private string informationField;
        
        private string poField;
        
        private string contactNameField;
        
        private string contactNoField;
        
        private string dBTRField;
        
        private string siteIdField;
        
        private System.DateTime expectedStartField;
        
        private System.DateTime expectedFinishField;
        
        private bool chargeableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerJobNo {
            get {
                return this.customerJobNoField;
            }
            set {
                this.customerJobNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickupName {
            get {
                return this.pickupNameField;
            }
            set {
                this.pickupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickupAddress {
            get {
                return this.pickupAddressField;
            }
            set {
                this.pickupAddressField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReadyTime {
            get {
                return this.readyTimeField;
            }
            set {
                this.readyTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DropoffName {
            get {
                return this.dropoffNameField;
            }
            set {
                this.dropoffNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DropoffAddress {
            get {
                return this.dropoffAddressField;
            }
            set {
                this.dropoffAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool ADR {
            get {
                return this.aDRField;
            }
            set {
                this.aDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PO {
            get {
                return this.poField;
            }
            set {
                this.poField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DBTR {
            get {
                return this.dBTRField;
            }
            set {
                this.dBTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SiteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpectedStart {
            get {
                return this.expectedStartField;
            }
            set {
                this.expectedStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpectedFinish {
            get {
                return this.expectedFinishField;
            }
            set {
                this.expectedFinishField = value;
            }
        }
        
        /// <remarks/>
        public bool Chargeable {
            get {
                return this.chargeableField;
            }
            set {
                this.chargeableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strJourneyResponse-Journey", Namespace="imcwp")]
    public partial class strJourneyResponseJourney {
        
        private string journeyIdField;
        
        private string journeyStatusField;
        
        private System.DateTime expectedStartField;
        
        private System.DateTime expectedFinishField;
        
        private strJourneyJob[] jobField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JourneyId {
            get {
                return this.journeyIdField;
            }
            set {
                this.journeyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JourneyStatus {
            get {
                return this.journeyStatusField;
            }
            set {
                this.journeyStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpectedStart {
            get {
                return this.expectedStartField;
            }
            set {
                this.expectedStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpectedFinish {
            get {
                return this.expectedFinishField;
            }
            set {
                this.expectedFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Job")]
        public strJourneyJob[] Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strJourneyRequest {
        
        private string numberPlateField;
        
        private string trailerIdField;
        
        private string journeyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumberPlate {
            get {
                return this.numberPlateField;
            }
            set {
                this.numberPlateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TrailerId {
            get {
                return this.trailerIdField;
            }
            set {
                this.trailerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JourneyId {
            get {
                return this.journeyIdField;
            }
            set {
                this.journeyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strTrailerResponse-Trailer", Namespace="imcwp")]
    public partial class strTrailerResponseTrailer {
        
        private string trailerIdField;
        
        private string trailerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TrailerId {
            get {
                return this.trailerIdField;
            }
            set {
                this.trailerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TrailerType {
            get {
                return this.trailerTypeField;
            }
            set {
                this.trailerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strTrailerRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strVehicleResponse-Vehicle", Namespace="imcwp")]
    public partial class strVehicleResponseVehicle {
        
        private int fleetNumberField;
        
        private string numberPlateField;
        
        /// <remarks/>
        public int FleetNumber {
            get {
                return this.fleetNumberField;
            }
            set {
                this.fleetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumberPlate {
            get {
                return this.numberPlateField;
            }
            set {
                this.numberPlateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strVehicleRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strTemplateResponse-Template", Namespace="imcwp")]
    public partial class strTemplateResponseTemplate {
        
        private string messageStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageString {
            get {
                return this.messageStringField;
            }
            set {
                this.messageStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strMessageTemplate {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strMessageReply {
        
        private string messageStringField;
        
        private System.DateTime messageTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageString {
            get {
                return this.messageStringField;
            }
            set {
                this.messageStringField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MessageTimestamp {
            get {
                return this.messageTimestampField;
            }
            set {
                this.messageTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="strMessageResponse-Message", Namespace="imcwp")]
    public partial class strMessageResponseMessage {
        
        private System.DateTime timestampClientField;
        
        private string messageStringField;
        
        private string userNameField;
        
        /// <remarks/>
        public System.DateTime TimestampClient {
            get {
                return this.timestampClientField;
            }
            set {
                this.timestampClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageString {
            get {
                return this.messageStringField;
            }
            set {
                this.messageStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strMessageRequest {
        
        private System.DateTime lastTimestampField;
        
        private System.DateTime lastReadTimestampField;
        
        /// <remarks/>
        public System.DateTime LastTimestamp {
            get {
                return this.lastTimestampField;
            }
            set {
                this.lastTimestampField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastReadTimestamp {
            get {
                return this.lastReadTimestampField;
            }
            set {
                this.lastReadTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="imcwp")]
    public partial class strLogin {
        
        private string deviceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class strLoginLoginResponse {
        
        private string sessionPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionPassword {
            get {
                return this.sessionPasswordField;
            }
            set {
                this.sessionPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class MessageRequest {
        
        private Header hdrField;
        
        private strMessageRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strMessageRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class strMessageRequestMessageResponse {
        
        private System.DateTime timestampField;
        
        private System.DateTime lastReadTimestampField;
        
        private strMessageResponseMessage[] messageField;
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastReadTimestamp {
            get {
                return this.lastReadTimestampField;
            }
            set {
                this.lastReadTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message")]
        public strMessageResponseMessage[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class MessageReply {
        
        private Header hdrField;
        
        private strMessageReply requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strMessageReply Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class strMessageReplyMessageReceived {
        
        private string messageReceivedOKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageReceivedOK {
            get {
                return this.messageReceivedOKField;
            }
            set {
                this.messageReceivedOKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class MessageTemplate {
        
        private Header hdrField;
        
        private strMessageTemplate requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strMessageTemplate Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class VehicleRequest {
        
        private Header hdrField;
        
        private strVehicleRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strVehicleRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class TrailerRequest {
        
        private Header hdrField;
        
        private strTrailerRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strTrailerRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class JourneyRequest {
        
        private Header hdrField;
        
        private strJourneyRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strJourneyRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class ConsignmentRequest {
        
        private Header hdrField;
        
        private strConsignmentRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strConsignmentRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class JourneyStatus {
        
        private Header hdrField;
        
        private strJourneyStatus requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strJourneyStatus Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class strJourneyStatusJourneyStatusResponse {
        
        private string statusField;
        
        private strJourneyStatusResponseValidStatus[] validStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValidStatus")]
        public strJourneyStatusResponseValidStatus[] ValidStatus {
            get {
                return this.validStatusField;
            }
            set {
                this.validStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class StatusRequest {
        
        private Header hdrField;
        
        private strStatusRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strStatusRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="imcwp")]
    public partial class DocumentRequest {
        
        private Header hdrField;
        
        private strDocumentRequest requestField;
        
        /// <remarks/>
        public Header Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }
        
        /// <remarks/>
        public strDocumentRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strLoginLoginResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strLoginLoginResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void MessageRequestCompletedEventHandler(object sender, MessageRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessageRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strMessageRequestMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strMessageRequestMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void MessageReplyCompletedEventHandler(object sender, MessageReplyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageReplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessageReplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strMessageReplyMessageReceived Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strMessageReplyMessageReceived)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void MessageTemplateCompletedEventHandler(object sender, MessageTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessageTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strTemplateResponseTemplate[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strTemplateResponseTemplate[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void VehicleRequestCompletedEventHandler(object sender, VehicleRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VehicleRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VehicleRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strVehicleResponseVehicle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strVehicleResponseVehicle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TrailerRequestCompletedEventHandler(object sender, TrailerRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrailerRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrailerRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strTrailerResponseTrailer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strTrailerResponseTrailer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void JourneyRequestCompletedEventHandler(object sender, JourneyRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JourneyRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strJourneyResponseJourney[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strJourneyResponseJourney[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ConsignmentRequestCompletedEventHandler(object sender, ConsignmentRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsignmentRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsignmentRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strConsignmentResponseRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strConsignmentResponseRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void JourneyStatusCompletedEventHandler(object sender, JourneyStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JourneyStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strJourneyStatusJourneyStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strJourneyStatusJourneyStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void StatusRequestCompletedEventHandler(object sender, StatusRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatusRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatusRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strStatusResponseStatusField[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strStatusResponseStatusField[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DocumentRequestCompletedEventHandler(object sender, DocumentRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocumentRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocumentRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strDocumentResponseDocument[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strDocumentResponseDocument[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591